# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZFwt1WictJwSn0B9d5bCedk80cMMtXb
"""

import re

# Langkah 1: Meminta input teks
teks = input("Masukkan teks: ")

# Langkah 2: Menghitung kata (Memecah berdasarkan spasi)
daftar_kata = teks.split()
jumlah_kata = len(daftar_kata)

# Langkah 3: Menghitung kalimat (Memecah berdasarkan titik & buang string kosong)
daftar_kalimat = [s for s in re.split(r'\.', teks) if s.strip()]
jumlah_kalimat = len(daftar_kalimat)

# Langkah 4: Menampilkan hasil
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")