# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgpvLJq140z7UM7YBry_W83UA1VSBdvT
"""

import re

# Langkah 1: Meminta input teks
import re
teks = input("Masukkan teks: ")

# Langkah 2: Memecah dan menghitung total kata
daftar_kata = teks.split()
total_kata = len(daftar_kata)

# Langkah 3: Mememcah dan menghitung total kalimat
daftar_kalimat = [s for s in re.split(r'\.', teks) if s.strip()]
total_kalimat = len(daftar_kalimat)

# Langkah 4: Menampilkan hasil
print(f"Teks tersebut memuat {total_kalimat} kalimat dan {total_kata} kata.")