# -*- coding: utf-8 -*-
"""02_string_kalimat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EiopPqwO4fFvmPiUT5EkNmJqO6uxKtd
"""

Kalimat1 = "Saya tak 'kan menyerah."
Kalimat2 = 'Ia berkata, "Aku menyayangimu."'
Kalimat3 = "\"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!\""
Kalimat4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(Kalimat1)
print(Kalimat2)
print(Kalimat3)
print(Kalimat4)