# -*- coding: utf-8 -*-
"""03_akar_kuadrat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUjYdOhdnbfjhYuNCi8BHlEZvN_D5jV0

## **BEFORE**
"""

import math

print("PROGRAM AKAR PERSAMAAN KUADRAT")

# Input koefisien
a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
c = float(input("Masukkan nilai c: "))

# Validasi
if a == 0:
    print("Error: Nilai a tidak boleh 0 karena bukan persamaan kuadrat.")
else:
    diskriminan = b**2 - 4*a*c

    if diskriminan < 0:
        print("Persamaan hanya memiliki akar-akar imajiner.")
    else:
        x1 = (-b + math.sqrt(diskriminan)) / (2*a)
        x2 = (-b - math.sqrt(diskriminan)) / (2*a)

        print(f"Akar pertama (x1) = {x1:.3f}")
        print(f"Akar kedua (x2) = {x2:.3f}")

"""## **AFTER**"""

import math

# Input koefisien
a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
c = float(input("Masukkan nilai c: "))

# Validasi
if a == 0:
    print("Error: Nilai a tidak boleh 0 karena bukan persamaan kuadrat.")
else:
    diskriminan = b**2 - 4*a*c

    if diskriminan < 0:
        print("Persamaan hanya memiliki akar-akar imajiner.")
    else:
        x1 = (-b + math.sqrt(diskriminan)) / (2*a)
        x2 = (-b - math.sqrt(diskriminan)) / (2*a)

        print(f"Akar pertama (x1) = {x1}")
        print(f"Akar kedua (x2) = {x2}")
