# -*- coding: utf-8 -*-
"""04_nip_asn.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mH2_jemcw2tWg2Y3mozl7QSOT10QiAvI
"""

import datetime

def Get_Nama_Bulan(Bulan: str) -> str:
    if Bulan == "01":
        return "Januari"
    elif Bulan == "02":
        return "Februari"
    elif Bulan == "03":
        return "Maret"
    elif Bulan == "04":
        return "April"
    elif Bulan == "05":
        return "Mei"
    elif Bulan == "06":
        return "Juni"
    elif Bulan == "07":
        return "Juli"
    elif Bulan == "08":
        return "Agustus"
    elif Bulan == "09":
        return "September"
    elif Bulan == "10":
        return "Oktober"
    elif Bulan == "11":
        return "November"
    elif Bulan == "12":
        return "Desember"
    else:
        return "Tidak Valid"

def Validasi_NIP(NIP: str) -> bool:
    if len(NIP) != 18:
        return False
    if not NIP.isdigit():
        return False
    return True

def Ekstrak_Tanggal_Lahir(NIP: str) -> tuple:
    Tahun   = NIP[0:4]
    Bulan   = NIP[4:6]
    Tanggal = NIP[6:8]
    return (Tahun, Bulan, Tanggal)

def Validasi_Tanggal(Tanggal: int, Bulan: int, Tahun: int) -> bool:
    try:
        datetime.datetime(Tahun, Bulan, Tanggal)
        return True
    except ValueError:
        return False

def Tampilkan_Tanggal_Lahir(NIP: str) -> None:
    print(f"\n{'='*45}")
    print(f"  NIP   : {NIP}")

    if not Validasi_NIP(NIP):
        Panjang = len(NIP)
        print(f"  Status: TIDAK VALID (panjang = {Panjang}, harus 18 digit angka)")
        print(f"{'='*45}\n")
        return
    Tahun, Bulan, Tanggal = Ekstrak_Tanggal_Lahir(NIP)
    Nama_Bulan = Get_Nama_Bulan(Bulan)

    # Convert Tanggal, Bulan, Tahun to int for validation and comparison
    Tanggal_int = int(Tanggal)
    Bulan_int = int(Bulan)
    Tahun_int = int(Tahun)

    if Nama_Bulan == "Tidak Valid" or not Validasi_Tanggal(Tanggal_int, Bulan_int, Tahun_int):
        print("  Status: TIDAK VALID (tanggal atau bulan di luar rentang)")
        print(f"{'='*45}\n")
        return
    print(f"  Tanggal Lahir: {Tanggal} {Nama_Bulan} {Tahun}")
    print(f"{'='*45}\n")

NIP = input("Masukkan NIP ASN: ").strip()
Tampilkan_Tanggal_Lahir(NIP)