# -*- coding: utf-8 -*-
"""04_nip_asn.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mH2_jemcw2tWg2Y3mozl7QSOT10QiAvI
"""

# ============================================================
#  Program: Menampilkan Tanggal Lahir ASN dari NIP
#  Bahasa : Python
#  Struktur: variabel, tipe data, operator, string,
#            percabangan, fungsi, list, operasi string
# ============================================================

def get_nama_bulan(bulan: int) -> str:
    """
    Mengembalikan nama bulan dalam Bahasa Indonesia
    menggunakan percabangan if-elif-else.

    Parameter:
        bulan (int): angka bulan (1–12)
    Returns:
        str: nama bulan
    """
    if bulan == 1:
        return "Januari"
    elif bulan == 2:
        return "Februari"
    elif bulan == 3:
        return "Maret"
    elif bulan == 4:
        return "April"
    elif bulan == 5:
        return "Mei"
    elif bulan == 6:
        return "Juni"
    elif bulan == 7:
        return "Juli"
    elif bulan == 8:
        return "Agustus"
    elif bulan == 9:
        return "September"
    elif bulan == 10:
        return "Oktober"
    elif bulan == 11:
        return "November"
    elif bulan == 12:
        return "Desember"
    else:
        return "Tidak Valid"


def validasi_nip(nip: str) -> bool:
    """
    Memvalidasi format NIP: harus 18 karakter dan semua digit.

    Parameter:
        nip (str): string NIP yang akan divalidasi
    Returns:
        bool: True jika valid, False jika tidak
    """
    if len(nip) != 18:
        return False
    if not nip.isdigit():
        return False
    return True


def ekstrak_tanggal_lahir(nip: str) -> tuple:
    """
    Mengekstrak komponen tanggal lahir dari NIP.
    8 digit pertama: YYYYMMDD

    Parameter:
        nip (str): NIP valid (18 digit)
    Returns:
        tuple: (tahun: str, bulan: int, tanggal: int)
    """
    tahun   = nip[0:4]          # 4 digit pertama  → tahun
    bulan   = int(nip[4:6])     # digit ke-5 & 6   → bulan (int)
    tanggal = int(nip[6:8])     # digit ke-7 & 8   → tanggal (int)
    return (tahun, bulan, tanggal)


def tampilkan_tanggal_lahir(nip: str) -> None:
    """
    Fungsi utama: menerima NIP dan menampilkan tanggal lahir.

    Parameter:
        nip (str): NIP yang diinputkan pengguna
    """
    print(f"\n{'='*45}")
    print(f"  NIP   : {nip}")

    # --- Validasi ---
    if not validasi_nip(nip):
        panjang = len(nip)
        print(f"  Status: TIDAK VALID (panjang = {panjang}, harus 18 digit angka)")
        print(f"{'='*45}\n")
        return

    # --- Ekstraksi ---
    tahun, bulan, tanggal = ekstrak_tanggal_lahir(nip)

    # --- Percabangan nama bulan ---
    nama_bulan = get_nama_bulan(bulan)

    # --- Validasi rentang tanggal/bulan ---
    if nama_bulan == "Tidak Valid" or tanggal < 1 or tanggal > 31:
        print("  Status: TIDAK VALID (tanggal atau bulan di luar rentang)")
        print(f"{'='*45}\n")
        return

    # --- Output ---
    print(f"  Tanggal Lahir: {tanggal} {nama_bulan} {tahun}")
    print(f"{'='*45}\n")


# ── Program Utama ─────────────────────────────────────────────
nip = input("Masukkan NIP ASN: ").strip()
tampilkan_tanggal_lahir(nip)