# -*- coding: utf-8 -*-
"""06_interval_proporsi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoH3kxKRFd4-mRIdMZuSoRm250l08UBD
"""

import math

def hitung_interval_konfidensi(p_hat: float, n: int, alpha: float) -> None:
    """
    Menghitung interval konfidensi (1 - alpha) untuk proporsi populasi p.

    Rumus:
        p_hat - z * sqrt(p_hat*(1-p_hat)/n)  <  p  <  p_hat + z * sqrt(p_hat*(1-p_hat)/n)

    Parameter:
        p_hat (float) : proporsi sampel (0 <= p_hat <= 1)
        n     (int)   : ukuran sampel
        alpha (float) : tingkat signifikansi (0.05 atau 0.10)
    """

    # Validasi proporsi
    if p_hat < 0 or p_hat > 1:
        print("Error: Proporsi sampel harus bernilai antara 0 dan 1.")
        return

    # Percabangan nilai z berdasarkan alpha
    if alpha == 0.10:
        z = 1.645
    elif alpha == 0.05:
        z = 1.96
    else:
        print("Error: Nilai alpha harus 10% (0.10) atau 5% (0.05).")
        return

    # Operasi matematika
    galat = z * math.sqrt((p_hat * (1 - p_hat)) / n)
    batas_bawah = p_hat - galat
    batas_atas  = p_hat + galat

    # Output hasil
    tingkat_kepercayaan = int((1 - alpha) * 100)
    print(f"\nHasil Interval Konfidensi {tingkat_kepercayaan}%:")
    print(f"  p_hat (proporsi sampel) : {p_hat}")
    print(f"  n (ukuran sampel)       : {n}")
    print(f"  z (alpha={alpha})        : {z}")
    print(f"  Galat                   : {galat:.4f}")
    print(f"  Interval Konfidensi     : {batas_bawah:.4f} < p < {batas_atas:.4f}")


# ── Program Utama ─────────────────────────────────────────────
p_hat = float(input("Masukkan proporsi sampel (p_hat): "))
n     = int(input("Masukkan ukuran sampel (n)       : "))
alpha = float(input("Masukkan alpha (0.05 atau 0.10)  : "))

hitung_interval_konfidensi(p_hat, n, alpha)